import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Yaantun Khaijan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-stone-800 px-5 py-2 flex justify-between items-center gap-5">
          <Link href={"/"}>
            <img src="/logo.png" alt="" className="w-[80px]" />
          </Link>

          <div className="space-x-5">
            <Link className="btn" href={"/foods"}>
              Foods
            </Link>
            <Link className="btn" href={"/reviews"}>
              Reviews
            </Link>
          </div>
        </header>
        <main className="px-5 py-8">{children}</main>
      </body>
    </html>
  );
}
